### PR TITLE
fixed eclipse import docs & netbeans cloned url

### PR DESCRIPTION
**Pull request by mohan08p**
Signed-off-by : Mohan Pawar <mohanpawary1990@gmail.com>

### CODE REVIEW

**Comment by ManoMarks** [comment]
@mohan08p can you sign your PR? https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work

@spara can you review?

**Comment by mohan08p** [comment]
Sorry... @ManoMarks

**Comment by ManoMarks** [comment]
No problem, thanks!

**Comment by torstenboe** [comment]
Hi Sophia,


sorry but that is what I'm using?


Best

Torsten


________________________________
Von: Sophia Parafina <notifications@github.com>
Gesendet: Montag, 14. November 2016 19:29
An: docker/labs
Betreff: Re: [docker/labs] fixed eclipse import docs & netbeans cloned url (#113)


@spara requested changes on this pull request.

The links are point to my personal repo, please correct the links to: https://github.com/docker/labs

[https://avatars0.githubusercontent.com/u/5429470?v=3&s=400]<https://github.com/docker/labs>

GitHub - docker/labs: This is a collection of tutorials ...<https://github.com/docker/labs>
github.com
README.md Docker Tutorials and Labs. This repo contains Docker labs and tutorials authored both by Docker, and by members of the community. We welcome contributions ...



-

**Comment by spara** [comment]
Torsten,

The canonical url should be the Docker labs repo, not my repo

screen shot 2016-11-15 at 9 20 38 am

**Comment by ManoMarks** [comment]
Fixed all the urls

**Pull request merged**
