### PR TITLE
Adding Install-DockerOnWS2016UsingDSC to Windows Containers Setup

### PR DESCRIPTION
**Pull request by ManoMarks**
@PlagueHQ @friism 

Signed-off by: Mano Marks <mano.marks@gmail.com>

### CODE REVIEW

**Comment by friism** [comment]
@ManoMarks awesome! - I think there are some problems with the markdown. Also, I think this should be represented as different installation methods instead of variants of the same thing (eg. maybe in separate doc - do you think it would make sense to split this out into win 10, and WS2016, and then have the two methods in the WS2016 one?). Basically, one is appropriate if you're wanting install Docker on individual servers. The other is appropriate if you're using [Windows PowerShell Desired State Configuration](https://msdn.microsoft.com/en-us/powershell/dsc/overview?f=255&MSPPError=-2147217396). We should also consider linking to the blog post: https://dscottraynsford.wordpress.com/2016/10/15/install-docker-on-windows-server-2016-using-dsc/

Curious about what @taylorb-microsoft thinks about this

**Comment by friism** [comment]
@ManoMarks ok..., I guess you disagree that it'd be advisable to cover this as two separate installation options.

**Comment by ManoMarks** [comment]
No I just wanted to get this out. I'll do a separate pr.

**Comment by PlagueHO** [comment]
Nice! Let me know if there is anything I can do to help. Looks like you've got it all covered nicely.

**Pull request merged**
