### PR TITLE
fixed tutorial on startup order: I fixed the app source code in other...

### PR DESCRIPTION
**Pull request by chanezon**
… repo to avoid the issue.

### CODE REVIEW

**Comment by ManoMarks** [comment]
@arun-gupta can you review?

**Comment by arun-gupta** [comment]
LGTM

**Comment by ManoMarks** [comment]
Thanks both of you!

**Comment by chanezon** [comment]
Thank you both. Arun, I fixed your war file as well: now it does not fail at startup, and waits for the bucket to be available.

**Comment by arun-gupta** [comment]
thanks @chanezon!

**Pull request merged**
